name: jupiter_clone
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  provider: ^6.0.5
  flutter_svg: ^2.0.5
  google_fonts: ^2.1.0
  sign_button: ^2.0.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  google_nav_bar: ^5.0.2
  flutter_excel: ^1.0.1
  file_picker: ^4.6.1
  csv: ^5.0.1
  path_provider: ^2.0.10
  open_file: ^3.2.1
  excel: ^2.1.0
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.7
  intl: ^0.17.0
  syncfusion_flutter_charts: ^21.1.41
  permission_handler: ^8.3.0
  http: ^0.13.4
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
